"""add sex

Revision ID: 07d1d1f3c9cb
Revises: 8629e7a5d312
Create Date: 2021-02-18 10:31:29.422368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d1d1f3c9cb'
down_revision = '8629e7a5d312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sexs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('sex_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'sexs', ['sex_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'sex_id')
    op.drop_table('sexs')
    # ### end Alembic commands ###
