"""add comment disabled

Revision ID: 157f1cbbb59f
Revises: 42a7e6da5080
Create Date: 2021-03-08 16:33:40.409133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157f1cbbb59f'
down_revision = '42a7e6da5080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disabled')
    # ### end Alembic commands ###
